definitions:
  handler.request:
    properties:
      code:
        type: string
      color:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  web.Response:
    properties:
      Data: {}
      Error:
        type: string
      code:
        type: string
    type: object
info:
  contact:
    name: API suppoer
    url: https://developers.mercadolibre.com.ar/support
  description: This API Handler MELI Products
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Bootcamp API
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: update one product in the Data Base
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: product to update
        in: body
        name: producy
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
      tags:
      - Products
swagger: "2.0"
